/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.TableColumnModel;


/**
 *
 * @author dyllan
 */
public class VistaLogeado extends javax.swing.JFrame {

    /**
     * Creates new form VistaLogeado
     */
    public VistaLogeado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        BotonPregunta = new javax.swing.JButton();
        BotonRespuesta = new javax.swing.JButton();
        BotonRecompensa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPreguntas = new javax.swing.JTable();
        BotonAceptarRespuesta = new javax.swing.JButton();
        tituloUsuario = new javax.swing.JLabel();
        TituloReputacion = new javax.swing.JLabel();
        InputUsuario = new javax.swing.JLabel();
        InputReputacion = new javax.swing.JLabel();
        BotonCrearEtiquetas = new javax.swing.JButton();
        BtnCerrarSesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonPregunta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonPregunta.setText("Realizar Pregunta");

        BotonRespuesta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonRespuesta.setText("Realizar Respuesta");
        BotonRespuesta.setPreferredSize(new java.awt.Dimension(145, 27));

        BotonRecompensa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonRecompensa.setText("Ofrecer Recompensa");
        BotonRecompensa.setPreferredSize(new java.awt.Dimension(170, 27));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenido a StackOverflow");

        TablaPreguntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Contenido", "FechaPublicacion", "Autor", "Recompensa", "AutorRecompesa", "Estado"
            }
        ));
        TablaPreguntas.setAlignmentX(1.0F);
        TablaPreguntas.setAlignmentY(1.0F);
        TablaPreguntas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TablaPreguntas.setMinimumSize(new java.awt.Dimension(200, 64));
        TablaPreguntas.setRowHeight(20);
        TablaPreguntas.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(TablaPreguntas);

        BotonAceptarRespuesta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonAceptarRespuesta.setText("Aceptar Respuesta");
        BotonAceptarRespuesta.setPreferredSize(new java.awt.Dimension(170, 27));
        BotonAceptarRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarRespuestaActionPerformed(evt);
            }
        });

        tituloUsuario.setText("Usuario");

        TituloReputacion.setText("Reputacion");

        InputUsuario.setText(".....");

        InputReputacion.setText(".....");

        BotonCrearEtiquetas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonCrearEtiquetas.setText("Crear Etiquetas");

        BtnCerrarSesion.setText("Cerrar Sesion");

        jLabel3.setText("Preguntas Realizadas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCerrarSesion)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonAceptarRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(BotonRecompensa, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(BotonCrearEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloUsuario)
                            .addComponent(TituloReputacion))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputReputacion)
                            .addComponent(InputUsuario))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloUsuario)
                            .addComponent(InputUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TituloReputacion)
                            .addComponent(InputReputacion))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonPregunta)
                    .addComponent(BotonRecompensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonAceptarRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(BotonRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonCrearEtiquetas)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(BtnCerrarSesion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAceptarRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAceptarRespuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaLogeado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonAceptarRespuesta;
    public javax.swing.JButton BotonCrearEtiquetas;
    public javax.swing.JButton BotonPregunta;
    public javax.swing.JButton BotonRecompensa;
    public javax.swing.JButton BotonRespuesta;
    public javax.swing.JButton BtnCerrarSesion;
    public javax.swing.JLabel InputReputacion;
    public javax.swing.JLabel InputUsuario;
    public javax.swing.JTable TablaPreguntas;
    private javax.swing.JLabel TituloReputacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel tituloUsuario;
    // End of variables declaration//GEN-END:variables
}
